#!/bin/bash

tool="caesar"

if grep -qi "debian" /etc/os-release 2>/dev/null || grep -qi "kali" /etc/os-release 2>/dev/null; then
    shared_folder="$HOME/.local/share"
    sbin_folder="$HOME/.local/bin"
    executable="caesar_executable"
elif [ -d "/data/data/com.termux/files/usr" ]; then
    shared_folder="/data/data/com.termux/files/usr/share"
    sbin_folder="/data/data/com.termux/files/usr/bin"
    executable="termux_executable"
else
    echo "Unsupported system. This script only supports Debian-based systems and Termux."
    exit 1
fi


shared="${shared_folder}/${tool}"
sbin="${sbin_folder}/${tool}"

# Prebuilt commands
if [ "$1" == "uninstall" ]; then
    echo "Uninstalling ${tool}..."
    rm -rf "${shared}" "${sbin}"
    echo "${tool} has been uninstalled successfully."
    exit 0
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "Usage: ${tool} [options] [arguments]"
    echo "Options:"
    echo "  -h, --help      Show this help message and exit"
    echo "  uninstall        Uninstall ${tool}"
    exit 0
fi

"${shared}/${executable}" $@